version: "3"

services:
  webserver:
    #image: drupal:8-apache
    build: .
    container_name: 'drupal'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mysql
    depends_on:
      - mysql
    volumes: 
      #- ${DOCUMENT_ROOT-./}:/var/www/html/sites
      - ./sites:/var/www/html/sites
  mysql:
    image: mysql:5.7
    container_name: 'mysql'
    restart: 'always'
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: tiger
